export const colors = {
  primary: '#FF6B35',
  primaryDark: '#8C3A1D',
  primaryText: '#FFFFFF',
  backgroundApp: '#EAF2F4',
  backgroundAuth: '#FFFFFF',
  surface: '#FFFFFF',
  surfaceAlt: '#F7F7F7',
  border: '#E6E6E6',
  text: '#1F2937',
  mutedText: '#6B7280',
  subtitleText: '#7A7A7A',
  inputBackground: '#F7F7F7',
  inputAltBackground: '#EFEFEF',
  success: '#1E8E3E',
  secondary: '#5B46CC',
  warning: '#F59E0B',
  info: '#1D5FBF',
  danger: '#FF3B30',
  dangerBackground: '#FFEBEE',
};
