export const colors = {
  primary: '#FF6B35',
  primaryText: '#FFFFFF',
  backgroundApp: '#EAF2F4',
  backgroundAuth: '#FFFFFF',
  surface: '#FFFFFF',
  surfaceAlt: '#F7F7F7',
  border: '#E6E6E6',
  text: '#1F2937',
  mutedText: '#6B7280',
  subtitleText: '#7A7A7A',
  inputBackground: '#F7F7F7',
  inputAltBackground: '#EFEFEF',
  success: '#34C759',
  secondary: '#7B61FF',
  warning: '#F59E0B',
  info: '#2F80ED',
  danger: '#FF3B30',
  dangerBackground: '#FFEBEE',
};
